name = "jobhackai-kv-d1-sync"
main = "src/index.js"
compatibility_date = "2024-12-11"

[triggers]
crons = ["0 * * * *"] # Hourly at the top of the hour

[env.dev]
name = "jobhackai-kv-d1-sync-dev"
d1_databases = [
  { binding = "JOBHACKAI_DB", database_id = "c5c0eee5-a223-4ea2-974e-f4aee5a28bab" }
]

[env.qa]
name = "jobhackai-kv-d1-sync-qa"
d1_databases = [
  { binding = "JOBHACKAI_DB", database_id = "80d87a73-6615-4823-b7a4-19a8821b4f87" }
]

[env.production]
name = "jobhackai-kv-d1-sync-prod"
d1_databases = [
  { binding = "JOBHACKAI_DB", database_id = "f9b709fd-56c3-4a0b-8141-4542327c9d4d" }
]


